name: Continuous Integration
on:
    push:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
            - '*.md'

env:
    CI: true

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [12.x, 14.x]
                os: [ubuntu-latest, windows-latest]
        name: Node ${{ matrix.node-version }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: yarn

            - name: Tests
              run: yarn test

            - name: Build
              run: yarn build
